from typing import Dict, Any
import tempfile
import os
import uuid

def generate_markdown(itinerary: Dict[str, Any]) -> str:
    """
    Generates a formatted Markdown string from the itinerary data.
    """
    md = []
    
    # --- Title & Header ---
    trip_title = itinerary.get("trip_title", "My Trip Itinerary")
    md.append(f"# 🌍 {trip_title}\n")
    
    if itinerary.get("summary_rationale"):
        md.append(f"> *{itinerary.get('summary_rationale')}*\n")
    
    # --- Trip Overview ---
    md.append("## 📝 Trip Overview\n")
    
    md.append("| Category | Details |")
    md.append("| :--- | :--- |")
    
    budget = itinerary.get("total_cost_estimate", "Moderate")
    md.append(f"| **💰 Est. Budget** | {budget} |")
    
    if itinerary.get("transportation_tips"):
        md.append(f"| **🚗 Transport** | {itinerary.get('transportation_tips')} |")
    
    if itinerary.get("accommodation_suggestion"):
        md.append(f"| **🏨 Stay** | {itinerary.get('accommodation_suggestion')} |")
        
    if itinerary.get("weather_forecast"):
        md.append(f"| **☀️ Weather** | {itinerary.get('weather_forecast')} |")
        
    md.append("\n---\n")

    # --- Daily Itinerary ---
    for day in itinerary.get("days", []):
        day_num = day.get("day_number")
        md.append(f"## 📅 Day {day_num}\n")
        
        for block in day.get("blocks", []):
            time_block = block.get("time_block", "Activity")
            start_time = block.get("start_time", "")
            end_time = block.get("end_time", "")
            poi = block.get("poi", {})
            name = poi.get("name", "Activity")
            desc = poi.get("description", "")
            category = poi.get("category", "")
            rating = poi.get("rating", "")
            cost = block.get("activity_cost") or poi.get("details", {}).get("cost", "Free")
            
            # Icon selection
            icon = "📍"
            if time_block == "Morning": icon = "☕"
            elif time_block == "Afternoon": icon = "☀️"
            elif time_block == "Evening": icon = "🌙"
            
            md.append(f"### {icon} {time_block}: {name}")
            md.append(f"**⏰ Time:** {start_time} - {end_time}  |  **🏷️ Type:** {category}  |  **⭐ Rating:** {rating}/5\n")
            
            if desc:
                md.append(f"{desc}\n")
            
            # Details List
            md.append(f"- **💸 Cost:** {cost}")
            if block.get("travel_time_from_previous"):
                md.append(f"- **🚕 Travel:** {block.get('travel_time_from_previous')}")
            
            # Tips / Secrets
            tip = block.get("local_tip") or poi.get("details", {}).get("tips")
            if tip:
                md.append(f"- **💡 Pro Tip:** {tip}")
                
            if poi.get("source_url"):
                md.append(f"- **🔗 More Info:** [Link]({poi.get('source_url')})")
            
            md.append("\n")
        
        md.append("---\n")
        
    # --- Final Footer ---
    md.append("Generated by **Voice AI Travel Assistant** 🤖✈️")
    
    return "\n".join(md)

def save_markdown_file(itinerary: Dict[str, Any]) -> str:
    """
    Generates markdown content and saves it to a temp file.
    Returns the file path.
    """
    content = generate_markdown(itinerary)
    
    # Create temp file
    unique_filename = f"trip_plan_{uuid.uuid4()}.md"
    temp_dir = tempfile.gettempdir()
    output_path = os.path.join(temp_dir, unique_filename)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    return output_path
