from fpdf import FPDF
import os

class ItineraryPDF(FPDF):
    def header(self):
        # Only put "Trip Itinerary" on the first page? Or everywhere? 
        # Let's put a subtle header on all pages
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'Generated by AI Travel Assistant', border=0, ln=0, align='R')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

def safe_text(text: str) -> str:
    """Sanitize text to be safe for FPDF (Latin-1)"""
    if not text:
        return ""
    text = str(text)
    # Replace common problematic characters
    text = text.replace('₹', 'Rs.').replace('—', '-').replace('–', '-').replace('"', '"').replace('"', '"')
    return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf(itinerary_data: dict, filename: str = "itinerary.pdf") -> str:
    """
    Generates a rich, multi-page PDF guide from the itinerary.
    """
    pdf = ItineraryPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # 1. FRONT PAGE / TITLE
    pdf.ln(20)
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(44, 62, 80) # Dark blue
    pdf.multi_cell(0, 12, safe_text(itinerary_data.get("trip_title", "Your Adventure")), align='C')
    pdf.ln(10)
    
    # Hero Summary
    if itinerary_data.get("summary_rationale"):
        pdf.set_font("Helvetica", "I", 12)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 6, safe_text(itinerary_data.get("summary_rationale")), align='C')
        pdf.ln(15)

    # 2. QUICK INFO BOX
    pdf.set_fill_color(245, 247, 250)
    pdf.rect(10, pdf.get_y(), 190, 45, 'F')
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(44, 62, 80)
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.cell(0, 7, "Trip Overview")
    pdf.ln(8)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(15)
    budget = itinerary_data.get("total_cost_estimate", "Moderate")
    pdf.cell(90, 6, f"Budget Estimate: {safe_text(budget)}")
    
    weather = itinerary_data.get("weather_forecast", "Check local app")
    pdf.set_x(110)
    pdf.cell(90, 6, f"Weather: {safe_text(weather)}")
    pdf.ln(7)
    
    pdf.set_x(15)
    transport = itinerary_data.get("transportation_tips", "Walk, Uber/Ola, Local Transport")
    pdf.multi_cell(180, 5, f"Transport: {safe_text(transport)}")
    
    pdf.set_x(15)
    hotel = itinerary_data.get("accommodation_suggestion", "Central city location")
    pdf.multi_cell(180, 5, f"Stay: {safe_text(hotel)}")
    pdf.ln(15)

    # 3. DAILY ITINERARY
    for day in itinerary_data.get("days", []):
        # Day Header
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_fill_color(52, 152, 219) # Blue
        pdf.set_text_color(255, 255, 255) # White
        pdf.cell(0, 12, f"  Day {day.get('day_number')}", fill=True, ln=True)
        pdf.ln(5)
        
        for block in day.get("blocks", []):
            # Check for page break space
            if pdf.get_y() > 230:
                pdf.add_page()

            # Time and Label
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(52, 152, 219)
            time_str = f"{block.get('start_time', '')} - {block.get('end_time', '')}"
            pdf.cell(45, 8, safe_text(block.get("time_block", "") + " | " + time_str), ln=False)
            
            # POI Name
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(44, 62, 80)
            poi = block.get("poi", {})
            pdf.cell(0, 8, safe_text(poi.get("name", "Free Time")), ln=True)
            
            # Cost and Link Sub-row
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(120, 120, 120)
            pdf.set_x(55)
            cost = block.get("activity_cost", "Free")
            link = poi.get("source_url", "")
            meta_str = f"Estimated Cost: {cost}"
            if link: meta_str += f"  |  More info: {link}"
            pdf.multi_cell(0, 5, safe_text(meta_str))
            
            # Description
            desc = poi.get("description", "")
            if desc:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(60, 60, 60)
                pdf.set_x(55)
                pdf.multi_cell(0, 5, safe_text(desc))
            
            # Tip
            tip = block.get("local_tip") or poi.get("details", {}).get("tips")
            if tip:
                pdf.ln(1)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(39, 174, 96) # Green
                pdf.set_x(55)
                pdf.multi_cell(0, 5, f"PRO TIP: {safe_text(tip)}")
            
            pdf.ln(8)
        
        pdf.ln(5)

    # FINAL ADVICE
    # FINAL ADVICE
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, "Final Tips for Your Trip", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 6, safe_text("• Keep some cash handy for small vendors.\n• Download an offline map of the city.\n• Respect local dress codes at religious sites.\n• Stay hydrated and enjoy the journey!"))

    # Use system temp directory and unique filename
    import tempfile
    import uuid
    
    unique_filename = f"itinerary_{uuid.uuid4()}.pdf"
    temp_dir = tempfile.gettempdir()
    output_path = os.path.join(temp_dir, unique_filename)
    
    pdf.output(output_path)
    return output_path
